version: '3.9'

services:

  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "MSSQL"
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
      test: ['CMD', '/opt/mssql-tools18/bin/sqlcmd', '-S', 'localhost,1433', '-U', 'sa', '-P', '${MSSQL_SA_PASSWORD}', '-No', '-Q', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: "MongoDB"
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--username=${MONGO_INITDB_ROOT_USERNAME}", "--password=${MONGO_INITDB_ROOT_PASSWORD}", "--quiet" ]
      interval: 10s
      timeout: 10s
      retries: 5

  eer.api:
    image: eer.api
    build:
      context: .
      dockerfile: ./src/EER.API/Dockerfile
    ports:
      - "5050:5050"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5050
    env_file:
      - .env
    depends_on:
      mssql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  sqlvolume:
  mongo_data:
