name: code-quality

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore

    - name: Enforce code style
      run: dotnet tool install -g dotnet-format && dotnet format --verify-no-changes

    - name: Build & Test
      run: dotnet build --configuration Release --no-restore --warnaserror
